# =========================
# DATAPACK BUILDER
# =========================

import os
import json

BASE_PATH = "./world/datapacks/modpack_analyzer"

class DatapackBuilder:

    def __init__(self):
        self.base = BASE_PATH

    def ensure_base(self):
        os.makedirs(self.base, exist_ok=True)

        # pack.mcmeta
        meta_path = os.path.join(self.base, "pack.mcmeta")

        if not os.path.exists(meta_path):
            with open(meta_path, "w") as f:
                json.dump({
                    "pack": {
                        "pack_format": 48,
                        "description": "Generated by Modpack Analyzer"
                    }
                }, f, indent=2)

    def save_recipe(self, namespace, path, data):
        self.ensure_base()

        full_path = os.path.join(
            self.base,
            "data",
            namespace,
            "recipes",
            path + ".json"
        )

        os.makedirs(os.path.dirname(full_path), exist_ok=True)

        with open(full_path, "w") as f:
            json.dump(data, f, indent=2)

        return full_path
